version: '3.7'

services:
  backend:
    build:
      context: ./backend
    command: yarn dev
    environment:
      - NODE_ENV=production
      - SERVE_STATIC=true
      - PORT=8080
    ports: 
      - 8080:8080
    depends_on: 
      - postgres      

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=knex
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=knex
    ports:
      - 5432:5432
      
