name: Build and deploy

on:
  push:
    branches:
      - master
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  IMAGE_NAME: gybsyregistry

jobs:
  build-frontend:
    name: Build frontend
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Use Node.js 14.x # is this needed?
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: build frontend
        working-directory: ./frontend
        run: yarn install && yarn run build-and-copy

      - name: Authenticate Cloud SDK
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          project_id: '${{ env.PROJECT_ID }}'
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Build and push to registry
        working-directory: ./backend
        run: gcloud builds submit --quiet --tag "eu.gcr.io/$PROJECT_ID/$IMAGE_NAME:latest"
# copy peistattu känässä:      
      - name: Deploy
        run: gcloud run deploy app --platform "managed" --image "eu.gcr.io/$PROJECT_ID/$IMAGE_NAME:latest" --region "europe-west6"

# GCP service account uses: Cloud run admin, Cloud build service account, viewer, storage admin, service account user