name: Build and deploy

on:
  push:
    branches:
      - master
#env:
  #PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  #IMAGE_NAME: helloworld

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps: 
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Use Node.js 14.x # is this needed?
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: build frontend
        working-directory: ./frontend
        run: yarn install && yarn run build-and-copy
      - name: List files
        working-directory: ./backend
        run: ls