name: Build and deploy

on:
  workflow_dispatch:    
  push:
    branches:
      - master
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  IMAGE_NAME: gybsyregistry

jobs:
  build-frontend:
    name: Build frontend and deploy
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Test custom action in it's own repo
        id: my-action
        uses: pimpbot9000/hello-world-action@v2
        with:
          who-to-greet: "Tumppu"

      - name: Test output of custom action
        run: |
          echo random-number ${{ steps.my-action.outputs.random-number }}
          echo test-output ${{ steps.my-action.outputs.test-output }}
          echo test-output2 ${{ steps.my-action.outputs.test-output2}}
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Test custom action in this repo
        uses: ./.github/actions/hello-world
        with:
          who-to-greet: "Tumppi"

      - name: Build frontend
        working-directory: ./frontend
        run: yarn install && yarn run build-and-copy

      - name: Authenticate Cloud SDK
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
          project_id: "${{ env.PROJECT_ID }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Build and push to registry
        working-directory: ./backend
        run: gcloud builds submit --quiet --tag "eu.gcr.io/$PROJECT_ID/$IMAGE_NAME:latest"

      - name: Deploy
        run: gcloud run deploy app --platform "managed" --image "eu.gcr.io/$PROJECT_ID/$IMAGE_NAME:latest" --region "europe-west6"

      - name: Set annotation
        if: always()
        run: echo "::notice title::Project ID::$(echo $IMAGE_NAME)" 
# GCP service account uses: Cloud run admin, Cloud build service account, viewer, storage admin, service account user
